### ISSUE TITLE
Explain what we aim to do easily on the homepage ASAP

### ISSUE THREAD

**Issue by bvhme** [publiccodenet/http#12]
Suggestion:

> We help public organisations develop and maintain software and policy together.

**Comment by bvhme** [comment]
Suggestion for text:

* Value: Quality, Cost, Control, Longevity
* How: We provide community, quality and marketing support as codebase stewardship for software and policy development projects.

**Comment by ElenaFdR** [comment]
Software can be public infrastructure

Cities can be empowered by their software choices: open source ftw!

The Foundation for Public Code will:
- help public organisations share their open source software
- build sustainable developer communities and create a thriving ecosystem for public code
- help public organisations adopt proven public code built by other public organisations


We do this in 2 ways:
- We publish the standard - The Standard for Public Code gives cities a model for building their own open source solutions to enable successful future reuse by other cities. It includes guidance for policymakers, city administrators, developers and vendors.
- We provide a platform for sharing proven software solutions developed by other cities, including maintenance, guidance, community support and advocacy- we call this codebase stewardship.


-----

We define ‘public code’ as open source software developed by public administrations (like cities), together with the policy and guidance needed for reuse.
