### ISSUE TITLE
Enforce HTTPS on all publiccode.net domains

### ISSUE THREAD

**Issue by attogram** [publiccodenet/http#27]
Enforce HTTPS on all publiccode.net domains.
* Maybe requires updating DNS?
* See: https://github.blog/2018-05-01-github-pages-custom-domains-https/

Domain Tests:

| Secure  | Non-Secure |
| ------------- | ------------- |
| https://publiccode.net/ | http://publiccode.net/ |
| https://about.publiccode.net/ | http://about.publiccode.net/ |
| https://blog.publiccode.net/ | http://blog.publiccode.net/ |
| https://brand.publiccode.net/ | http://brand.publiccode.net/ |
| https://smartcities.publiccode.net/ | http://smartcities.publiccode.net/ |
| https://standard.publiccode.net/ | http://standard.publiccode.net/ |

**Comment by bvhme** [comment]
I've redirected the `http` on all of them to https to enforce `https` on the DNS/server side.

Tested all those links.

Is this the resolution on do you also mean enforcing this on the body links?

**Comment by attogram** [comment]
This is the resolution, yes.   All tests passed on my end.

**Comment by attogram** [comment]
issue done.  closing ticket.
