### ISSUE TITLE
cover image....

### ISSUE THREAD

**Issue by paul2keller** [publiccodenet/http#9]
has this any deeper meaning? the street is part of my paris running route (see blue dot on screenshot below), interesting to see it in this context :)

![screen shot 2018-04-20 at 13 49 41](https://user-images.githubusercontent.com/5593766/39049560-40f19396-44a2-11e8-87de-171430812f23.png)

**Comment by bvhme** [comment]
Hey @paul2keller!

Indeed, we've picked exactly this location *because* it is on your running path. It is important to us that you feel at home on our website.

I feel we can only resolve this issue over 🍻 beers though.
